import { type Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap", // Better performance
});

export const metadata: Metadata = {
  title: "Admin | Urban Rush Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" className={inter.variable}>
        <body className="antialiased overflow-hidden font-sans">
          {children}
        </body>
      </html>
    </Providers>
  );
}
